#spring:
#  datasource:
#    url: jdbc:postgresql://${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    show-sql: true

security:
  jwt:
    secret-key: secretTest

