spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_database_username
    password: your_database_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: secretTest
